{% set native = 'm2w64-' if win else '' %}
{% set posix = 'm2-' if win else '' %}
{% set version = "4.3.1" %}

package:
  name: r-base-split
  version: {{ version }}

source:
  - url: https://cran.r-project.org/src/base/R-4/R-{{ version }}.tar.gz
    sha256: 8dd0bf24f1023c6f618c3b317383d291b4a494f40d73b983ac22ffea99e4ba99
    patches:
      - 0001-Darwin-Remove-unicode-elipsis-character-from-grDevic.patch
      - 0002-Fix-trio-config.h-include-depth-issue.patch
      - 0003-Win32-Do-not-link-static-libgcc.patch
      - 0004-Win32-Extend-sqrt-NA_real_-hack-to-all-GCC-versions.patch
      - 0005-Win32-Prevent-conversion-of-R_ARCH-to-abs-Windows-pa.patch
      - 0006-Darwin-Avoid-setting-DYLD_FALLBACK_LIBRARY_PATH.patch
      - 0008-Linux-Do-not-modify-LD_LIBRARY_PATH.patch
      - 0009-javareconf-Do-not-fail-on-compile-fail.patch
      - 0010-Revert-part-of-9b818c6dc00143ff18775a4015a3f43b5196f.patch
      - 0011-javareconf-macOS-Continue-to-allow-system-Java-lt-9-.patch
      #- 0012-Allow-rpath-in-tcltk-dylib-LC_LOAD_DYLIB-command.patch
      - 0015-Check-for-changes-then-forcibly-mv-in-javareconf.in.patch
      - 0016-Use-LAPACK_LDFLAGS-in-Rlapack_la_LIBADD.patch
      - 0017-tcltk-dylib-osx.patch
  # The following are used for the Mingw_w64 builds, added in
  # https://github.com/conda-archive/conda-recipes/commit/959fa4bb8b14c522e5f791d1463c9bc0021059e0
  - url: http://constexpr.org/innoextract/files/innoextract-1.6/innoextract-1.6-windows.zip  # [win]
    sha256: 33d61133401bb6a919b299f282b5e8f0aada67253460b0c11c85b56cdb1ea0d3                 # [win]
    folder: win-extra-files/innoextract                                                      # [win]
  - url: http://files.jrsoftware.org/is/5/innosetup-5.5.9-unicode.exe                        # [win]
    sha256: 5b51ae6977bebba937ac18e0e80c1899e37dfaa12f51ccd817978ef07ae19cb3                 # [win]
    folder: win-extra-files                                                                  # [win]

build:
  skip: True  # [not x86_64]
  number: 5
  no_link:
    - lib/R/doc/html/packages.html

outputs:
  - name: r-base
    script: build-r-base.sh  # [not win]
    script: bld-r-base.bat  # [win]
    build:
      merge_build_host: true  # [win]
      rpaths:
        - lib/R/lib/
        - lib/
      no_link:
        # These files are modified by R CMD javareconf and can
        # point to different Java implementations in each env.
        - lib/R/etc/Makeconf
        - lib/R/etc/ldpaths
        - lib/R/etc/javaconf
        - lib/R/etc/x64/Makeconf
        - lib/R/etc/x64/ldpaths
        - lib/R/etc/x64/javaconf
      detect_binary_files_with_prefix: true
    requirements:
      build:
        - gnuconfig                          # [unix]
        - {{ compiler('c') }}                # [not win]
        - {{ compiler('cxx') }}              # [not win]
        - {{ compiler('fortran') }}          # [not win]
        - mingw-w64-ucrt-x86_64-gcc          # [win]
        - mingw-w64-ucrt-x86_64-gcc-fortran  # [win]
        # For gendef
        - mingw-w64-ucrt-x86_64-tools-git    # [win]
        - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
        - {{ cdt('libxrender') }}            # [linux]
        - {{ cdt('libxext') }}               # [linux]
        - {{ cdt('libsm-devel') }}           # [linux]
        - {{ cdt('libice-devel') }}          # [linux]
        - {{ cdt('libx11-devel') }}          # [linux]
        - {{ cdt('libxt') }}                 # [linux]
        - {{ cdt('libxt-devel') }}           # [linux]
        - {{ cdt('libxcb') }}                # [linux]
        - {{ cdt('libxau') }}                # [linux]
        - {{ cdt('java-1.7.0-openjdk') }}    # [linux]
        - {{ posix }}pkg-config
        - posix                              # [win]
        - m2-texinfo-tex                     # [win]
        - m2-texinfo                         # [win]
        - m2-curl                            # [win]
        - m2-p7zip                           # [win]
        - miktex                             # [win]
        #- texlive-core                       # [unix]
        - texinfo                            # [unix]
        - openjdk
        - {{ posix }}autoconf
        - {{ posix }}automake-wrapper        # [win]
        - automake                           # [not win]
        - make                               # [not win]
        - libcurl                            # [not win]
        - readline                            # [build_platform != target_platform]
        - libcurl                             # [build_platform != target_platform]
        - xz                                  # [build_platform != target_platform]
        - libpng                              # [build_platform != target_platform]
        - bzip2                               # [build_platform != target_platform]
        - cairo                               # [build_platform != target_platform]
        - libjpeg-turbo                       # [build_platform != target_platform]
        - libiconv                            # [unix and (build_platform != target_platform)]
        - glib                                # [unix and (build_platform != target_platform)]
        - bwidget                             # [build_platform != target_platform]
        - tktable                             # [build_platform != target_platform]
        - pango                               # [build_platform != target_platform]
        - icu                                 # [build_platform != target_platform]
        - pcre2                               # [build_platform != target_platform]
        - tk                                  # [build_platform != target_platform]
        - zlib                                # [build_platform != target_platform]
        - libtiff                             # [build_platform != target_platform]
        - libblas                             # [build_platform != target_platform]
        - liblapack                           # [build_platform != target_platform]
        - llvm-openmp                         # [osx]
        - libgomp                             # [linux]
      host:
        - readline                           # [not win]
        - libcurl
        - xz
        - libpng
        - bzip2
        - cairo
        - gettext                            # [osx]
        - fontconfig                         # [osx or win]
        - libjpeg-turbo
        - libiconv
        - libuuid                            # [linux]
        - glib                               # [unix]
        - bwidget
        - tktable
        - pango                              # [not win]
        - icu
        - pcre2
        - tk
        - zlib
        - gsl
        - libtiff
        - libblas                            # [not win]
        - liblapack                          # [not win]
        # sed is in host env because its path is recorded in R's shell wrapper
        - sed                                # [linux]
        - mingw-w64-ucrt-x86_64-gcc-libs            # [win]
        - mingw-w64-ucrt-x86_64-gcc-libgfortran     # [win]
      run:
        - _r-mutex 1.* anacondar_1
        # Needed by R CMD javareconf
        - make                               # [not win]
        - gcc_impl_{{ target_platform }}  >={{ c_compiler_version|default("0") }}    # [linux]
        - gxx_impl_{{ target_platform }}  >={{ cxx_compiler_version|default("0") }}  # [linux]
        - gfortran_impl_{{ target_platform }}  # [linux]
        - {{ c_compiler|default("blah") }}_{{ target_platform }} >={{ c_compiler_version|default("0") }}      # [osx]
        - {{ cxx_compiler|default("blah") }}_{{ target_platform }} >={{ cxx_compiler_version|default("0") }}  # [osx]
        - {{ compiler('fortran') }}  # [osx]
        - {{ pin_compatible('llvm-openmp', max_pin=None) }}      # [osx]
        - curl
        - libuuid                              # [linux]
        - xorg-libxt                           # [linux]
        - bwidget
        - tktable
        - tk
        - sed                                # [linux]
        - mingw-w64-ucrt-x86_64-gcc-libs            # [win]
        - mingw-w64-ucrt-x86_64-gcc-libgfortran     # [win]

    test:
      commands:
        - R -h
        - R --version
        - R -e "print(.Platform\$dynlib.ext)"    # [not win]
        - R -e \"print(.Platform$dynlib.ext)\"   # [win]
        - R -e "library('tcltk')"                # [not win]
        - R -e \"library('tcltk')\""             # [win]
        - Rscript --version
        - Rscript -e  'cat("ok\\n")'
        # Report on the optional features compiled into this build of R.
        - R -e "capabilities()"              # [not win]
        - R -e \"capabilities()\""           # [win]
        # Show third-party graphics software available
        - R -e "grSoftVersion()"             # [not win]
        - R -e \"grSoftVersion()\""          # [win]
        # TODO does not work on windows, because winCairo.dll is missing
        - Rscript test-svg.R                 # [not win]
        - open                               # [win]
         # There doesn't seem to be a way to test this one
         # - RSetReg                         # [win]
        - Rfe --help                         # [win]
        - Rterm --help                       # [win]
        - Rterm --version                    # [win]
        # Prevent regression mentioned in https://github.com/conda-forge/r-base-feedstock/issues/50
        - Rscript -e "stopifnot(capabilities('jpeg'), TRUE)"
        - Rscript -e "stopifnot(capabilities('png'), TRUE)"
        - if not exist %PREFIX%\\Lib\\R\\bin\\x64\\R.lib exit 1  # [win]
      files:
        - test-svg.R


  - name: cross-r-base
    build:
      skip: true  # [win]
    script: install-cross-activate.sh
    requirements:
      run:
        - {{ pin_subpackage("r-base", exact=True) }}
        - rsync
    test:
      commands:
        - test -f $PREFIX/etc/conda/activate.d/activate-cross-r-base.sh

about:
  home: http://www.r-project.org/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: R is a free software environment for statistical computing and graphics.

extra:
  feedstock-name: r-base
  recipe-maintainers:
    - conda-forge/r
    - isuruf
    - mbargull
    - mingwandroid
    - ocefpaf
    - sodre
    - xhochy
