bot:
  abi_migration_branches:
  - 4.0.x
build_platform:
  osx_arm64: osx_64
conda_forge_output_validation: true
azure:
  store_build_artifacts: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: native
  linux_ppc64le: native
test_on_native_only: true
